### ISSUE TITLE
Issue in the retrieval section

### ISSUE THREAD

**Issue by GuilaumeBrassard** [yumoxu/querysum#4]
Hi again!

I encounter an issue while running the ir_tf.py file in the "Retrival" section. I get the following error: 
Exception has occurred: AttributeError
'list' object has no attribute 'lower'
  File "/data/lm953/summarization/querysum/src/tools/tfidf_tools.py", line 18, in get_counts
    counts = count_vec.fit_transform(sents)
  File "/data/lm953/summarization/querysum/src/tools/tfidf_tools.py", line 30, in get_tf_mat
    counts = get_counts(sents)
  File "/data/lm953/summarization/querysum/src/tools/tfidf_tools.py", line 73, in _compute_rel_scores_tf
    tf_mat = get_tf_mat(sents=doc_sents)
  File "/data/lm953/summarization/querysum/src/tools/tfidf_tools.py", line 175, in build_rel_scores_tf
    rel_scores = _compute_rel_scores_tf(processed_sents, query)
  File "/data/lm953/summarization/querysum/src/frame/ir/ir_tf.py", line 30, in _rank
    res = tfidf_tools.build_rel_scores_tf(cid, query)
  File "/data/lm953/summarization/querysum/src/frame/ir/ir_tf.py", line 78, in rank_e2e
    rank_records = _rank(**params)
  File "/data/lm953/summarization/querysum/src/frame/ir/ir_tf.py", line 189, in <module>
    rank_e2e()
I suppose that the get_counts() function needs a list of strings and not a list of lists of strings like it is imputed there. I am not sure if I did something wrong to get a list of lists as "sents" imput or if the ir_tf.py file is not updated in the repo.

Thanks for the support!

**Comment by yumoxu** [comment]
Hi @GuilaumeBrassard, sorry for the late reply!

I am not able to replicate your problem; the 2D list has been flattened in the following code in `_compute_rel_scores_tf`:

https://github.com/yumoxu/querysum/blob/62a7b09f9825a0ff673c75eb502e062e0b34f844/src/tools/tfidf_tools.py#L69

Can you please provide the config you are using and try printing out `doc_sents` and `processed_sents` inside `_compute_rel_scores_tf`?

**Comment by GuilaumeBrassard** [comment]
Hi @yumoxu,

Here is the abridged print of doc_sents : [[["washington, novemb 8 (xinhua) -- unit state ... 'congress enact veto 1996, clinton 82 time year.']]]
Here is the abridged print of processed_sents : [["washington, novemb 8 (xinhua) -- unit state ... 'congress enact veto 1996, clinton 82 time year.']]

I fixed it by changing the code to receive a 2d list and not a 3d list. It seems to be working and I completed the "Retrieval" section in the README.

Sadly, I have issues with the installation of Nvidia-Apex which prevent me to continue with the "Answering" section. This is the error : 

Traceback (most recent call last):
  File "src/frame/bert_qa/main.py", line 405, in <module>
    run(prep=True, mode='rec')
  File "src/frame/bert_qa/main.py", line 387, in run
    dump_rel_scores()
  File "src/frame/bert_qa/main.py", line 241, in dump_rel_scores
    _dump(model, cluster_loader=cluster_loader, dump_dp=rel_scores_dp)
  File "src/frame/bert_qa/main.py", line 126, in _dump
    feed_dict['token_masks'])
  File "/home/guillaumed/anaconda3/envs/querysum/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guillaumed/anaconda3/envs/querysum/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 820, in forward
    output_all_encoded_layers=False)
  File "/home/guillaumed/anaconda3/envs/querysum/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guillaumed/anaconda3/envs/querysum/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 626, in forward
    embedding_output = self.embeddings(input_ids, token_type_ids)
  File "/home/guillaumed/anaconda3/envs/querysum/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guillaumed/anaconda3/envs/querysum/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 198, in forward
    embeddings = self.LayerNorm(embeddings)
  File "/home/guillaumed/anaconda3/envs/querysum/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guillaumed/anaconda3/envs/querysum/lib/python3.6/site-packages/apex/normalization/fused_layer_norm.py", line 159, in forward
    input, self.weight, self.bias, self.normalized_shape,self.eps)
  File "/home/guillaumed/anaconda3/envs/querysum/lib/python3.6/site-packages/apex/normalization/fused_layer_norm.py", line 18, in forward
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/home/guillaumed/anaconda3/envs/querysum/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fused_layer_norm_cuda'


I tried installing Apex with cuda_ext fallowing this solution https://github.com/NVIDIA/apex/issues/161 without success. Did you used this method to install Apex or something else?

Thanks again!

**Comment by yumoxu** [comment]
Hi @GuilaumeBrassard, I used the following commands to install apex:

```
git clone https://github.com/NVIDIA/apex
cd apex
pip install -v --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```

If my recall is right, I got stuck here with a similar problem. In my case, GCC version was the problem; it should be between 4.9 and 6.0 for apex and support your CUDA version. 

You may find [this issue](https://github.com/NVIDIA/apex/issues/278) helpful.

**Comment by JeetRoy97** [comment]
![Screenshot from 2021-08-23 18-44-53](https://user-images.githubusercontent.com/59523992/130453717-b3bfe5bf-281b-4325-913b-5ed79095657e.png)

I am getting this even after the @yumoxu solution. Is there any other way around?

**Comment by elevenofji** [comment]
> ![Screenshot from 2021-08-23 18-44-53](https://user-images.githubusercontent.com/59523992/130453717-b3bfe5bf-281b-4325-913b-5ed79095657e.png)
> 
> I am getting this even after the @yumoxu solution. Is there any other way around?

seems like apex installation problem.
